Fix: Fix reset not working
jsun969/react-hook-form-antd pull request #75
Opened 2024-02-18 20:10 UTC by avegatolber

2024-02-22 15:49 UTC, jsun969 requested changes
thx for the contribution. Just a little suggestion for import.

2024-02-22 15:49 UTC, jsun969 commented on src/FormItem.tsx
> +  React.useEffect(() => {
```suggestion
  useEffect(() => {
```

2024-02-22 15:49 UTC, jsun969 commented on src/FormItem.tsx
> +import React from 'react';
```suggestion
import { useEffect } from 'react';
```

2024-02-22 15:57 UTC, avegatolber commented on src/FormItem.tsx
> +import React from 'react';
I just made a new commit with these changes

2024-02-22 16:34 UTC, jsun969 approved these changes
LGTM

2024-02-22 16:35 UTC, merged

2024-02-27 06:50 UTC, jsun969 commented
@all-contributors please add @avegatolber for code, bug